[book]
authors = ["Otto Kokstein"]
language = "en"
multilingual = false
src = "src"
title = "Otto Kokstein"

[build]
create-missing = true

[output.html]
git-repository-url = "https://github.com/ottokokstein/ottokokstein.github.io/"
