[book]
authors = ["Otto Kokstein"]
language = "en"
multilingual = false
src = "src"
title = "Otto Kokstein"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/ottokokstein/ottokokstein.github.io/"
default-theme = "ayu"
additional-css = ["theme/pagetoc.css", "theme/css/adjustments.css"]
additional-js = ["theme/pagetoc.js"]
