[book]
authors = ["Otto Kokstein"]
language = "en"
multilingual = false
src = "src"
title = "Otto Kokstein"

[preprocessor.theme]
pagetoc = false
pagetoc-width = "15%"
content-max-width = "80%"
page-padding = "25px"
sidebar-width = "300px"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/ottokokstein/ottokokstein.github.io/"
additional-css = ["theme/pagetoc.css", "css/custom.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false
