name: Build and Deploy mdBook

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache mdBook
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook
          key: mdbook-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install mdBook if not cached
        run: |
          if ! command -v mdbook &> /dev/null; then
            cargo install mdbook
          fi

      - name: Clean previous build
        run: mdbook clean

      - name: Build mdBook
        run: mdbook build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
